feat: release v3.2.0
sighupio/fury-kubernetes-registry pull request #23
Opened 2024-10-29 13:48 UTC by stefanoghinelli

Changes included in this PR:
- update docs (readme, comp matrix, release notes)
- update tests
- refactor CI to use Kind

Resolves: [504](https://github.com/sighupio/product-management/issues/504)

2024-10-30 12:00 UTC, ralgozino requested changes
overwall great job!

is this PR just for the CI and you will open another one bumping harbor version or are we not updating harbor for some reason?

2024-10-30 13:12 UTC, stefanoghinelli commented on .drone.yml
> +      - curl -LOs https://github.com/sighupio/furyctl/releases/download/v0.11.1/furyctl-linux-amd64 && chmod +x furyctl-linux-amd64 && mv furyctl-linux-amd64 /usr/local/bin/furyctl
Nope, the e2e-testing image in 1.28 and 1.29 pipelines has furyctl `0.11.0` pre-installed. To maintain consistency and use the same `furyctl vendor -H `command used in `setup.sh` tests, we need to keep using version `0.11.0` in the newer as well.

2024-10-30 17:15 UTC, stefanoghinelli commented on .drone.yml
> +      - curl -LOs https://github.com/sighupio/furyctl/releases/download/v0.11.1/furyctl-linux-amd64 && chmod +x furyctl-linux-amd64 && mv furyctl-linux-amd64 /usr/local/bin/furyctl
Done.

2024-10-30 17:18 UTC, stefanoghinelli commented on .drone.yml
> +      KIND_CONFIG: ./katalog/tests/harbor/config/kind-config
Done.

2024-10-30 17:19 UTC, stefanoghinelli commented
Talking with Sam, I understood that bumping harbor version is out of scope for this release and not currently required. Right @nutellinoit?

2024-10-30 17:37 UTC, ralgozino requested changes
> Talking with Sam, I understood that bumping harbor version is out of scope for this release and not currently required. Right @nutellinoit?

I mean, that's totally fine, but if that is the case then we don't need to do a new release, because there is no point in updating the module from a user perspective because there are absolutely no changes.

Checking if upstream is compatible, updating the tests, docs, etc. (i.e. what you did in this PR) is enough to have the module compatible with the newer versions IMO.

So, I'd say to remove the release notes for 3.2.0 and this PR is 🟢 .

Alternatively, if we want/need to do a release, let's be more specific in the release notes that the release does not practically change anything and that can be ignored.

2024-11-04 08:05 UTC, stefanoghinelli commented
As discussed, I updated the release notes to clarify that this release is purely for Kubernetes compatibility testing and doesn't include changes.

2024-11-04 08:11 UTC, ralgozino approved these changes
perfect!

2024-11-04 08:33 UTC, merged